import = ["/home/danirod/.config/alacritty/xterm.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 10.5

[font.normal]
family = "DejaVuSansM Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control"
